//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultorioWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamento
    {
        public int DepartamentoId { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> ProvinciaId { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual Provincia Provincia { get; set; }
    }
}
