//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultorioWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoConsultorio
    {
        public int id { get; set; }
        public string NombreConsultorio { get; set; }
        public string Dirección { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string DiasyHorariosAtencion { get; set; }
        public string Web { get; set; }
        public string Mision { get; set; }
        public string Vision { get; set; }
        public string Descripcion { get; set; }
    }
}
