//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultorioWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SegurosMedicosMedico
    {
        public int Id { get; set; }
        public int IdMedico { get; set; }
        public int IdSeguroMedico { get; set; }
    
        public virtual Medico Medico { get; set; }
        public virtual SegurosMedico SegurosMedico { get; set; }
    }
}
