//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consultorio.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bancos_Tarjetas
    {
        public int Id { get; set; }
        public int IdTarjeta { get; set; }
        public int IdBanco { get; set; }
    
        public virtual Bancos Bancos { get; set; }
        public virtual Tarjetas Tarjetas { get; set; }
    }
}
