//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consultorio.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.Turno = new HashSet<Turno>();
        }
    
        public int IdFactura { get; set; }
        public int IdTurno { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdFormaDePago { get; set; }
        public decimal Monto { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdTarjeta { get; set; }
    
        public virtual FormaDePago FormaDePago { get; set; }
        public virtual Tarjetas Tarjetas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Turno> Turno { get; set; }
    }
}
