//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consultorio.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoriaClinica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HistoriaClinica()
        {
            this.Paciente = new HashSet<Paciente>();
        }
    
        public int IdHistoriaClinica { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime UltimaActualizacion { get; set; }
        public string AntecedentesMedicos { get; set; }
        public string GrupoSanguineo { get; set; }
        public bool Donante { get; set; }
        public bool Transplantado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paciente> Paciente { get; set; }
    }
}
