//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consultorio.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineaFactura
    {
        public int IdLineaFactura { get; set; }
        public int IdFactura { get; set; }
        public int IdTurno { get; set; }
        public string Descripcion { get; set; }
        public decimal Monto { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Turno Turno { get; set; }
    }
}
