//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consultorio.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineaFactura
    {
        public int IdLineaFactura { get; set; }
        public int IdFactura { get; set; }
        public int IdTurno { get; set; }
        public string Descripcion { get; set; }
        public decimal Monto { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Turno Turno { get; set; }
    }
}
