//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consultorio.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medico()
        {
            this.Factura = new HashSet<Factura>();
            this.MedicoEspecialidad = new HashSet<MedicoEspecialidad>();
            this.PersonalInterno = new HashSet<PersonalInterno>();
            this.SegurosMedicosMedico = new HashSet<SegurosMedicosMedico>();
            this.Turno = new HashSet<Turno>();
        }
    
        public int IdMedico { get; set; }
        public string MatriculaMedico { get; set; }
        public int LunesHorarioId { get; set; }
        public int MartesHorarioId { get; set; }
        public int MiercolesHorarioId { get; set; }
        public int JuevesHorarioId { get; set; }
        public int ViernesHorarioId { get; set; }
        public int SabadoHorarioId { get; set; }
        public int DomingoHorarioId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura { get; set; }
        public virtual Horario Horario { get; set; }
        public virtual Horario Horario1 { get; set; }
        public virtual Horario Horario2 { get; set; }
        public virtual Horario Horario3 { get; set; }
        public virtual Horario Horario4 { get; set; }
        public virtual Horario Horario5 { get; set; }
        public virtual Horario Horario6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicoEspecialidad> MedicoEspecialidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalInterno> PersonalInterno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SegurosMedicosMedico> SegurosMedicosMedico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Turno> Turno { get; set; }
    }
}
