//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consultorio.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente_Tarjetas
    {
        public int Id { get; set; }
        public int IdPaciente { get; set; }
        public int IdTarjeta { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual Tarjetas Tarjetas { get; set; }
    }
}
