//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consultorio.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalInterno
    {
        public int IdPersonal { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public long NumeroDocumento { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Sexo { get; set; }
        public string EstadoCivil { get; set; }
        public string TelCel { get; set; }
        public string Email { get; set; }
        public bool Activo { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> IdCiudad { get; set; }
        public Nullable<int> IdProvincia { get; set; }
        public Nullable<int> IdPais { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdMedico { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual Medico Medico { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual Provincia Provincia { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
