//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consultorio.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno
    {
        public int IdTurno { get; set; }
        public int IdMedico { get; set; }
        public int IdPaciente { get; set; }
        public int IdFormaDePago { get; set; }
        public System.DateTime FechaYHora { get; set; }
        public Nullable<int> IdSeguroMedico { get; set; }
        public string Diagnostico { get; set; }
        public string Descripcion { get; set; }
        public bool Asistio { get; set; }
        public bool Atendido { get; set; }
        public decimal PrecioTurno { get; set; }
        public int IdEspecialidadMedico { get; set; }
        public Nullable<int> IdFactura { get; set; }
    
        public virtual Especialidad Especialidad { get; set; }
        public virtual Factura Factura { get; set; }
        public virtual FormaDePago FormaDePago { get; set; }
        public virtual Medico Medico { get; set; }
        public virtual Paciente Paciente { get; set; }
        public virtual SegurosMedico SegurosMedico { get; set; }
    }
}
