//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepositoDeAlimentos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClasificaEn
    {
        public int IdClasificaEn { get; set; }
        public int IdProducto { get; set; }
        public int IdCategoria { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
