//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepositoDeAlimentos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FichaInventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FichaInventario()
        {
            this.ListaVerificacion = new HashSet<ListaVerificacion>();
        }
    
        public int IdFichaInventario { get; set; }
        public int IdLote { get; set; }
        public string CodigoEstadoLote { get; set; }
        public Nullable<int> Año { get; set; }
        public Nullable<System.DateTime> Semana { get; set; }
        public string OberservacionesGenerales { get; set; }
        public int IdTecnicoBromatologico { get; set; }
    
        public virtual EstadoLote EstadoLote { get; set; }
        public virtual Lote Lote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaVerificacion> ListaVerificacion { get; set; }
        public virtual TecnicoBromatologico TecnicoBromatologico { get; set; }
    }
}
