//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepositoDeAlimentos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaVerificacion
    {
        public int IdListaVerificacion { get; set; }
        public int IdVerificacion { get; set; }
        public int IdFichaInventario { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public string Resultado { get; set; }
    
        public virtual FichaInventario FichaInventario { get; set; }
        public virtual Verificacion Verificacion { get; set; }
    }
}
